stages:
  preprocess:
    cmd: python 1.preprocessing.py ./data/sentiment_tagged_data ./data/sentiment_train_data
    deps:
    - ./data/sentiment_tagged_data
    outs:
    - ./data/sentiment_train_data/datasets.json

  train:
    cmd: python 3.train.py
    deps:
    - ./data/sentiment_train_data/datasets.json
    params:
      - params.py:
        - MODEL
        - TrainConfig.EPOCHS
        - TrainConfig.BATCH_SIZE