stages:
  preprocess:
    cmd: python 1.preprocessing.py ./data/sentiment_tagged_data ./data/sentiment_train_data
    deps:
    - 1.preprocessing.py
    - ./data/sentiment_tagged_data
    outs:
    - ./data/sentiment_train_data/datasets.json

  train:
    cmd: python 3.train.py
    deps:
    - 3.train.py
    - ./data/sentiment_train_data/datasets.json
    params:
      - params.py:
        - MODEL
        - TRAINED_MODEL
        - TrainConfig.EPOCHS
        - TrainConfig.BATCH_SIZE
        - TrainConfig.LEARNING_RATE
        - TrainConfig.PER_DEVICE_TRAIN_BATCH_SIZE
        - TrainConfig.PER_DEVICE_EVAL_BATCH_SIZE
        - TrainConfig.WEIGHT_DECAY